dist: trusty
sudo: false
language: c

compiler:
  - gcc

addons:
  apt:
    sources:
    - sourceline: 'ppa:linuxjedi/ppa'
    packages:
    - build-essential
    - libjson-c-dev
    - libevent-dev
    - libip4tc-dev

script:
  - cmake .
  - make
